import type { Metadata } from "next";
import { Electrolize } from "next/font/google";
import "./components/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const electrolize = Electrolize({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-electrolize",
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pl" className={electrolize.variable}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
